spring:
  redis:
    host: localhost
    password:
    port: 6379
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        serverAddr: localhost:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8081
    gateway:
      enabled: true
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: mesh-auth-server
          uri: lb://mesh-auth-server
          predicates:
            - Path=/oauth/**,/auth/**
        - id: business_service_route
          uri: lb://mesh-business-service
          predicates:
            - Path=/nacos/**,/bar/{segment}
#            - Cookie=JSESSIONID, 89B45328A3FF57837046CAAAE490916F
#            - Header=X-Request-Id, \d+
#            - Method=GET
#            - Query=baz
#            - RemoteAddr=192.168.1.1/20
          filters:
            - StripPrefix=1
#            - AddRequestHeader=X-Request-Foo, Bar
#            - AddRequestParameter=foo, bar
#            - AddResponseHeader=X-Response-Foo, Bar

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://admin:123123@127.0.0.1:8830/eureka/
    preferIpAddress: true

#Authorization Signature switch(True: Checking)
checkSign: false

# https://ahas.console.aliyun.com/?spm=a2cb8.12805554.0.0.6bf71e63lvtCGv#/SystemGuardGw?ns=default&regionId=public&isi=&_k=li7w04
#ahas:
#  namespace: default
#  license: c997cffd0c7148efa3e64042dfa6cca5
#project:
#  name: mesh-gateway

management.endpoints.web.exposure.include: '*'